---
abstract: 'DBIx::Class profiler'
author:
  - 'Andrey Kostenko <andrey@kostenko.name>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-QueryProfiler
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  parent: 0
  perl: 5.8.9
resources:
  license: http://dev.perl.org/licenses/
  repository: http://developers.rambler.ru/svn/perlmodules/DBIx-Class-QueryProfiler/
version: 0.03
